# -----------------------
# Site Settings
# -----------------------
title: Giorgio Micaletto
email: gmicaletto@uchicago.edu
author: Giorgio
description: >- # This renders below your title or in SEO tags. Keep it under 160 characters.
  PhD Student in Statistics at the University of Chicago. 
  Background spanning applied mathematics, computer science, and data-driven research.

# -----------------------
# URL Settings
# -----------------------
baseurl: "/GiorgioMB"
url: "https://giorgiomb.github.io/"

# -----------------------
# Social Integration
# -----------------------
github_username:  GiorgioMB
linkedin_username: giorgio-micaletto

# -----------------------
# Build Settings
# -----------------------
theme: jekyll-theme-minimal

# Exclude these files from the build process to keep the site fast
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# -----------------------
# Markdown Processing (Supports LaTeX)
# -----------------------
markdown: kramdown
kramdown:
  math_engine: mathjax
